name: Michael Lek
favicon: null
layout_spectrum: 0.734971369151026
typography_spectrum: 0.7785881150048226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9944009201135486
  lightness: 0.24663408985361457
  saturation: 0.9729559011757374
  rhythmicContrast: 0.2872347394004464
purpose: []
